# Generated by Django 2.1.5 on 2019-10-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191021_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='column',
        ),
    ]
